events {
    worker_connections 1024;
}

http {
    # FastAPI UI
    server {
        listen 8000;

        auth_basic "NetPulse";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location / {
            proxy_pass http://app:8000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Authorization "";
        }
    }

    # Prometheus
    server {
        listen 9090;

        auth_basic "NetPulse";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location / {
            proxy_pass http://prometheus:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization "";
        }
    }

    # Blackbox Exporter
    server {
        listen 9115;

        auth_basic "NetPulse";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location / {
            proxy_pass http://blackbox:9115;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization "";
        }
    }
}
